name: docker
description: 'build the docker image'

inputs:
  app:
    required: true
  gitRef:
    required: true
    description: 'the git ref to be used as tag'

runs:
  using: 'composite'
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: use node default docker image
      if: contains(fromJson('["svc1", "svc2", "svc3"]'), inputs.app)
      shell: bash
      run: echo "dockerfile=./dockerfiles/Dockerfile.node" >> $GITHUB_ENV"

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tags: test-nx/${{ inputs.app }}:${{ inputs.gitRef }}
        file: ${{ env.dockerfile }}
        build-args: |
          app=${{ inputs.app }}
