name: dispatch
on: push
jobs:
  get-affected:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install nx
        run: npm install -g nx
      - name: get affected
        id: get-affected
        run: |
          affected=$(nx print-affected | jq -c '.projects')
          echo '::set-output name=dispatch_to::$affected'
          ::debug::$affected
    outputs:
      affected: ${{ steps.get-affected.outputs.affected }}

  dispatch:
    runs-on: ubuntu-latest
    needs: get-affected
    strategy:
      matrix:
        projects: ${{ fromJson(needs.get-affected.outputs.affected) }}
    steps:
      - run: echo ${{ matrix.projects }}
      - name: dispatch to ci
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          event-type: affected
          client-payload: '{"ref": "${{ github.ref }}", project": "${{ matrix.affected }}"}'

