name: dispatch
on: push
jobs:
  get-affected:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install nx
        run: npm install -g nx
      - name: install
        run: npm install
      - name: get affected
        id: get-affected-projects
        run: echo ::set-output name=affected::$(nx print-affected | jq -rc ".projects")
    outputs:
      affected: ${{ steps.get-affected-projects.outputs.affected }}

  dispatch:
    runs-on: ubuntu-latest
    needs: get-affected
      #strategy:
      #  matrix:
      #    project: ${{ fromJson(needs.get-affected.outputs.affected) }}
    steps:
      - run: echo ${{needs.get-affected.outputs.affected}}
        #- name: dispatch to ci
        #  uses: peter-evans/repository-dispatch@v1
        #  with:
        #    token: ${{ secrets.PAT }}
        #    event-type: affected
        #    client-payload: '{"ref": "${{ github.ref }}", "project": "${{ matrix.project }}"}'

